- name: Deploy Frontend
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: Remove the default content of web server
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent

    - name: Download and unzip frontend content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /tmp/
        remote_src: yes

    - name: Add Nginx Reverse Proxy Configuration
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf


    - name: Start & Enable Nginx service
      ansible.builtin.systemd_service:
        name: nginx
        state: started
        enabled: true



